{
    'extends':
        [
            'stylelint-config-standard',
            'stylelint-config-prettier',
            'stylelint-prettier/recommended',
        ],
    'rules': { 'selector-class-pattern': null },
}
